apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: online-boutique
  namespace: argocd
spec:
  project: OB

  source:
    repoURL: https://github.com/AdarshJain-dev/OnlineBuitique-CD.git
    targetRevision: main
    path: release

  destination:
    server: https://kubernetes.default.svc
    namespace: webapps

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
